### ISSUE TITLE
Binaries for *nix platforms.

### ISSUE THREAD

**Issue by Ed-Fernando** [lanmessenger/lanmessenger#1]
I really appreciate that you've restarted development after years :smiley: 

I want to enquire about support for Linux/macOS especially installer packages for Ubuntu, as I don't see releases for them.

**Comment by lanmessenger** [comment]
Done.

**Comment by Ed-Fernando** [comment]
I had to install **libqt5xml5**,**libqt5webkit5** & **libqt5multimedia5** on my Ubuntu 16.04 system. There maybe more dependencies, do feel free to mention them if you feel so.

Thanks a ton!
