### ISSUE TITLE
The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by aacsus** [lanmessenger/lanmessenger#15]
I installed LAN Messenger V1.2.37 on both my ThinkPad laptop and HP Desktop. While it worked flawlessly on the ThinkPad, it refused to install/work on the desktop. Both machines use up to date Windows 10.

During installation, an error window opens and it says: "The application was unable to start correctly (0xc000007b). Click OK to close the application." The installation stops. Then, I click "OK", and the installation quits. When I try to run LAN Messenger, it comes up with the same error message.
I tried to install, then run as "Administrator", but nothing changed.

I checked msvcr120.dll. It looks normal. I downloaded and reinstalled it, I copied it to system32 and to SysWOW64, but no help.

I am also using FreeCAD. If there was a problem, FreeCAD would not run either, right?
![install run_error](https://user-images.githubusercontent.com/38672472/47251184-4b5a9800-d3e5-11e8-86fa-77d1f0956205.png)

**Comment by LeoLeo1985** [comment]
Solve: you must find msvcr120_clr0400.dll (for axample in folder SYSWOW64), rename it to msvcr120.dll and put this file in to LAN Messenger folder. It really works. Have a nice day.

Решение проблемы: находите файл msvcr120_clr0400.dll (например в папке SYSWOW64), переименовываете в msvcr120.dll и копируете в папку программы. Проверено - работает. Удачи.

**Comment by lanmessenger** [comment]
Fixed in v1.2.39
