### ISSUE TITLE
Fresh Windows 10 Insatllation of lmc-1.2.37-win32.exe fails 

### ISSUE THREAD

**Issue by jcnezbeth** [lanmessenger/lanmessenger#9]
During installation of lmc-1.2.37-win32.exe on a machine with a fresh installation of Windows 10 (with all updates including Fall Creators Edition) it fails with the returned message "cannot find msvcr120.dll".
After re-downloading the dll and installing in windows\system32 directory and checking the file with sfc.exe the installation still fails with the error reported.
However on the same machine, installation of lmc-1.2.35-win32.exe is successful.

**Comment by lanmessenger** [comment]
Fixed in v1.2.39
